### ISSUE TITLE
Cannot generate "model id"  from step4

### ISSUE THREAD

**Issue by GhadaJouini** [NanoNets/nanonets-id-card-digitization#2]
when I run the command : "python ./code/training.py" the "model_id" is not generated, and this error occurs:

Traceback (most recent call last):
  File "./code/training.py", line 10, in <module>
    model = OCR(API_KEY, CATEGORIES)
  File "/usr/local/lib/python3.6/dist-packages/nanonets/ocr.py", line 17, in __init__
    self.create_model(categories)
  File "/usr/local/lib/python3.6/dist-packages/nanonets/ocr.py", line 46, in create_model
    self.model_id = response.json()["model_id"]
KeyError: 'model_id'

any solution how to fix this and thanks :)

**Comment by rushabhnagda11** [comment]
Have you set NANONETS_API_KEY as an env variable?

**Comment by GhadaJouini** [comment]
yes using this command  " !export NANONETS_API_KEY= my API key" @rushabhnagda11

**Comment by CloneHub94** [comment]
I also get this error. Citing an error 500(Internal server error) when I print response
![image](https://user-images.githubusercontent.com/37849398/101043245-63b6ae00-357e-11eb-833c-104554a40555.png)
:

**Comment by CloneHub94** [comment]
This is the code inside my training.py file:

import os
from nanonets import OCR

API_KEY = os.environ.get('NANONETS_API_KEY')
CATEGORIES = ['name', 'sex', 'date_of_birth', 'address', 'dl_number', 'issue_date', 'exp_date', 'class', 'height', 'restrictions', 'eyes']

IMAGE_DIR = './images/'
ANNOTATION_DIR = './annotations/json/'

model = OCR(API_KEY, CATEGORIES)

images = [IMAGE_DIR + x for x in os.listdir(IMAGE_DIR)]
images.sort()

annotations = [ANNOTATION_DIR + x for x in os.listdir(ANNOTATION_DIR)]
annotations.sort()

training_dict = dict(zip(images, annotations))

response = model.train(training_dict)

print("NEXT RUN: export NANONETS_MODEL_ID=" + model.model_id)
print("NEXT RUN: python ./code/model-state.py")
